### ISSUE TITLE
Issue with search for free slots and "_include" not working properly

### ISSUE THREAD

**Issue by james-answer** [nhs-digital/gpconnect-demonstrator#17]
An issue was raised as per below:

> I am making a call to your demonstrator where I want it to return free slots. I would like it to return extra info as well to avoid another trip.
>  
> The REST url I am using is:
>  
> Slot?start=ge2018-02-01T00:00:00+00:00&end=le2018-02-15T00:00:00+00:00&fb-type=free&_include=Slot:schedule&_include:recurse=Schedule.actor:Practitioner&_include:recurse=Schedule.actor:Location
>  
> …this returns a Bad Request even though it complies with the format/parameters given in your docs.
>  
> A more simple request:
>  
> Slot?start=ge2018-02-01T00:00:00+00:00&end=le2018-02-15T00:00:00+00:00&fb-type=free&_include=Slot:schedule
>  
> …works fine.

**Comment by Chrisjobling** [comment]
Bug fixed pushed to STU3 branch
