### ISSUE TITLE
Remove the extra meme types,

### ISSUE THREAD

**Issue by james-answer** [nhs-digital/gpconnect-demonstrator#21]
Remove the extra meme types, spec is going to be updated for version 1.0.0 and 1.1.0

Servers should also support DSTU2 MIME-types for backwards compatibility:

Servers SHALL support JSON: application/json+fhir
Servers SHOULD support XML: application/xml+fhir

Servers should also graceful handling generic XML and JSON MIME types:

Servers SHALL support JSON: application/json
Servers SHALL support JSON: text/json
Servers SHOULD support XML: application/xml

Put strict validation to only allow:
    XML: application/fhir+xml
    JSON: application/fhir+json
To make sure consumers send correct ones.

**Comment by Chrisjobling** [comment]
Extra meme types removed
