### ISSUE TITLE
For all ‘invalid request parameter names and case-1 to xx” tests the response is correct ie 422 but the OperationOutcome states Patient not found/Invalid NHS number

### ISSUE THREAD

**Issue by Chrisjobling** [nhs-digital/gpconnect-demonstrator#6]
<?xml version="1.0" encoding="UTF-8"?>
<OperationOutcome xmlns="http://hl7.org/fhir">
            <meta>
                        <profile value="http://fhir.nhs.net/StructureDefinition/gpconnect-operationoutcome-1"/>
            </meta>
            <issue>
                        <severity value="error"/>
                        <code value="not-found"/>
                        <details>
                                    <coding>
                                                <system value="http://fhir.nhs.net/ValueSet/gpconnect-error-or-warning-code-1"/>
                                                <code value="INVALID_NHS_NUMBER"/>
                                    </coding>
                                    <text value="Patient Record Not Found"/>
                        </details>
            </issue>
</OperationOutcome>
 
 
It should be INVALID PAPAMETER
Ie
 
<?xml version="1.0" encoding="UTF-8"?>
<OperationOutcome xmlns="http://hl7.org/fhir">
            <meta>
                        <profile value="http://fhir.nhs.net/StructureDefinition/gpconnect-operationoutcome-1"/>
            </meta>
            <issue>
                        <severity value="error"/>
                        <code value=" invalid"/>
                        <details>
                                    <coding>
                                                <system value="http://fhir.nhs.net/ValueSet/gpconnect-error-or-warning-code-1"/>
                                                <code value=" INVALID_PARAMETER "/>
                                    </coding>
                                    <text value=" Invalid parameter: [xxxxxxxxxxxxxxxxxxxxxxxxx]</"/>
                        </details>
            </issue>
</OperationOutcome>

**Comment by james-answer** [comment]
This has now been resolved.
